Save last used class in $cclass.$userinfo and use it to set the current library when loading the library
suransys/go-to-class pull request #7
Opened 2018-10-09 22:56 UTC by Frogli

2018-10-14 21:46 UTC, barkingfoodog requested changes
@Frogli this looks good. I think we can remove the class variable and use use `$cclass.$userinfo`. If you'll push these changes, I'll merge this over.

2018-10-14 21:46 UTC, barkingfoodog commented on src/go_to_class/wdGoToClass/$_getLibrary.omh
> +Quit method $libs.[pick(isclear($cclass.$userinfo),$cclass.$userinfo,ilLibraries.Name)]
I would keep this line the same since we're getting the library that's currently selected, which is stored in `ilLibraries`.

2018-10-14 21:46 UTC, barkingfoodog commented on src/go_to_class/wdGoToClass/$construct.omh
> +If isclear(ciCurrentLibraryLine)
Let's eliminate `ciCurrentLibraryLine` altogether and just use `$class.$userinfo`.

2018-10-14 21:46 UTC, barkingfoodog commented on src/go_to_class/wdGoToClass/objs/dlLibrary/$event.omh
>  	Calculate ciCurrentLibraryLine as ilLibraries.$line
We can remove this assignment as part of taking out `ciCurrentLibraryLine`.

2018-10-16 13:29 UTC, Frogli commented
Refactored the ciLibraryLine out of the code and changed it all to the `$class.$userinfo`

2018-10-16 14:17 UTC, Frogli commented
I am not sure how to create separate pull requests for commits. Anyways, I think attached to this pull request is also the change of the complexgrid background color.

2018-10-18 15:38 UTC, barkingfoodog approved these changes

2018-10-18 15:38 UTC, merged

2018-10-18 15:39 UTC, barkingfoodog commented
Looks good. Yeah, you can use some git-fu to revert the commit for the background color, stash it, then apply it to another branch and make a separate PR. But that's way too much work for tweaking a simple background color.